/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AttestationRegistry {
  export type AttestationStruct = {
    docHash: BytesLike;
    subject: AddressLike;
    verifierId: string;
    timestamp: BigNumberish;
  };

  export type AttestationStructOutput = [
    docHash: string,
    subject: string,
    verifierId: string,
    timestamp: bigint
  ] & {
    docHash: string;
    subject: string;
    verifierId: string;
    timestamp: bigint;
  };
}

export interface AttestationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "attest" | "attestations" | "get"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Attested"): EventFragment;

  encodeFunctionData(
    functionFragment: "attest",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "attestations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "get", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
}

export namespace AttestedEvent {
  export type InputTuple = [
    docHash: BytesLike,
    subject: AddressLike,
    verifierId: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    docHash: string,
    subject: string,
    verifierId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    docHash: string;
    subject: string;
    verifierId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AttestationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AttestationRegistry;
  waitForDeployment(): Promise<this>;

  interface: AttestationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attest: TypedContractMethod<
    [docHash: BytesLike, subject: AddressLike, verifierId: string],
    [void],
    "nonpayable"
  >;

  attestations: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint] & {
        docHash: string;
        subject: string;
        verifierId: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  get: TypedContractMethod<
    [docHash: BytesLike],
    [AttestationRegistry.AttestationStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [docHash: BytesLike, subject: AddressLike, verifierId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attestations"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint] & {
        docHash: string;
        subject: string;
        verifierId: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "get"
  ): TypedContractMethod<
    [docHash: BytesLike],
    [AttestationRegistry.AttestationStructOutput],
    "view"
  >;

  getEvent(
    key: "Attested"
  ): TypedContractEvent<
    AttestedEvent.InputTuple,
    AttestedEvent.OutputTuple,
    AttestedEvent.OutputObject
  >;

  filters: {
    "Attested(bytes32,address,string,uint256)": TypedContractEvent<
      AttestedEvent.InputTuple,
      AttestedEvent.OutputTuple,
      AttestedEvent.OutputObject
    >;
    Attested: TypedContractEvent<
      AttestedEvent.InputTuple,
      AttestedEvent.OutputTuple,
      AttestedEvent.OutputObject
    >;
  };
}
